### PR TITLE
Fixed regex matching.

### PR DESCRIPTION
**Pull request by Kill4Free**
Fixed the regex matching.

Before: Three characters of the string has been assigned to number, guid and name.
(One to each)

### CODE REVIEW

**Comment by indepth666** [comment]
Thanks. I'll review this during the weekend and I'll merge after.

**Comment by Kill4Free** [comment]
No problem 👍

**Comment by ole1986** [comment]
@Kill4Free very good you added the OnReconnect event.

can you tell me when it got fired?

**Comment by Kill4Free** [comment]
The onReconnect event is fired if we lost connection and receive another authenticad packet.

**Pull request merged**
